name: ABdfn
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/ 
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
dependencies:
  - python=3.9
  - cudatoolkit
  - pip
  - pip:
    - torch==2.0.0
    - torchvision
    - huggingface-hub==0.18.0
    - matplotlib==3.7.0
    - iopath
    - regex==2022.10.31
    - tqdm==4.64.1
    - transformers==4.30.0
    - timm==0.6.13
    - webdataset==0.2.48
    - omegaconf==2.3.0
    - opencv-python==4.7.0.72
    - sentence-transformers
    - scikit-image
    - wandb -i https://pypi.tuna.tsinghua.edu.cn/simple
